# Generated by Django 4.2.3 on 2023-07-19 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=20, null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automovel.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Automovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('cor', models.CharField(blank=True, max_length=20, null=True)),
                ('nr_portas', models.IntegerField(blank=True, null=True, verbose_name='Número de portas')),
                ('tipo_combustivel', models.CharField(choices=[('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('diesel', 'Diesel'), ('flex', 'Flex'), ('eletrico', 'Elétrico')], default='gasolina', max_length=10)),
                ('quilometragem', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('renavam', models.IntegerField(blank=True, null=True)),
                ('chassi', models.CharField(blank=True, max_length=20, null=True)),
                ('valor_locacao', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço de locação')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automovel.modelo')),
            ],
        ),
    ]
