# Generated by Django 4.2.3 on 2023-07-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0004_automovel_ano_fabricacao_alter_automovel_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovel',
            name='ano_fabricacao',
            field=models.IntegerField(),
        ),
    ]
