# Generated by Django 4.2.3 on 2023-07-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0005_alter_automovel_ano_fabricacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovel',
            name='descricao',
            field=models.TextField(default='', max_length=300),
        ),
    ]
