# Generated by Django 4.2.3 on 2023-07-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0006_automovel_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovel',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
