# Generated by Django 4.2.3 on 2023-07-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0007_automovel_disponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovel',
            name='disponivel',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='tipo_combustivel',
            field=models.CharField(choices=[('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('diesel', 'Diesel'), ('flex', 'Flex'), ('eletrico', 'Elétrico')], default='flex', max_length=10),
        ),
    ]
