# Generated by Django 4.2.3 on 2023-07-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0008_alter_automovel_disponivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovel',
            name='cor',
            field=models.CharField(choices=[('Branco', 'Branco'), ('Preto', 'Preto'), ('Prata', 'Prata'), ('Vermelho', 'Vermelho'), ('Azul', 'Azul'), ('Verde', 'Verde'), ('Amarelo', 'Amarelo'), ('Laranja', 'Laranja'), ('Rosa', 'Rosa'), ('Roxo', 'Roxo')], default='Branco', max_length=20),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='nr_portas',
            field=models.IntegerField(default=4, verbose_name='Número de portas'),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='placa',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='tipo_combustivel',
            field=models.CharField(choices=[('Gasolina', 'Gasolina'), ('Etanol', 'Etanol'), ('Diesel', 'Diesel'), ('Flex', 'Flex'), ('Eletrico', 'Elétrico')], default='Flex', max_length=10),
        ),
    ]
