# Generated by Django 4.2.3 on 2023-07-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0009_alter_automovel_cor_alter_automovel_nr_portas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovel',
            name='imagem',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='quilometragem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='renavam',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='valor_locacao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Preço de locação'),
        ),
    ]
