# Generated by Django 4.2.3 on 2023-07-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0010_alter_automovel_imagem_alter_automovel_quilometragem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovel',
            name='descricao',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='valor_locacao',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço de locação'),
        ),
    ]
