# Generated by Django 4.2.3 on 2023-07-30 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0011_alter_automovel_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='images/adicionais/%Y/%m/%d/')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='automovel.automovel')),
            ],
        ),
        migrations.AddField(
            model_name='automovel',
            name='imagens_adicionais',
            field=models.ManyToManyField(blank=True, to='automovel.imagemcarro'),
        ),
    ]
