# Generated by Django 4.2.3 on 2023-07-30 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0012_imagemcarro_automovel_imagens_adicionais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automovel',
            name='imagens_adicionais',
        ),
        migrations.DeleteModel(
            name='ImagemCarro',
        ),
    ]
