# Generated by Django 4.2.3 on 2023-08-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0013_remove_automovel_imagens_adicionais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovel',
            name='ano_fabricacao',
            field=models.IntegerField(verbose_name='Ano de Fabricação'),
        ),
    ]
