# Generated by Django 4.2.3 on 2023-08-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0014_alter_automovel_ano_fabricacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovel',
            name='chassi',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='marca',
            name='descricao',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='descricao',
            field=models.CharField(default='', max_length=20),
        ),
    ]
