# Generated by Django 4.2.3 on 2023-07-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Completo')),
                ('cpf', models.CharField(blank=True, max_length=30, null=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(related_name='usuarios', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='usuarios', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
