# Generated by Django 4.2.3 on 2023-07-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usuario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
