# Generated by Django 4.2.3 on 2023-08-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0013_alter_locacao_cliente_alter_locacao_quilometragem'),
        ('accounts', '0005_alter_user_telefone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
