# Generated by Django 4.2.3 on 2023-07-19 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('automovel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_locacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Locação')),
                ('data_devolucao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Devolução')),
                ('quilometragem', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_locacao', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço de Locação')),
                ('devolvido', models.BooleanField(blank=True, null=True)),
                ('automovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automovel.automovel')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
