# Generated by Django 4.2.3 on 2023-08-10 22:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automovel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_locacao', models.DateField(default=datetime.date, verbose_name='Data de Locação')),
                ('data_devolucao', models.DateField(default=datetime.date, verbose_name='Data de Devolução')),
                ('hora_locacao', models.TimeField(default=1691708114.3752763, verbose_name='Hora de Locação')),
                ('hora_devolucao', models.TimeField(default=1691708114.3752763, verbose_name='Hora de Devolução')),
                ('quilometragem', models.IntegerField(default=0)),
                ('valor_locacao', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço de Locação')),
                ('devolvido', models.BooleanField(blank=True, null=True)),
                ('limite_km_dia', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Retirado', 'Retirado'), ('Cancelado', 'Cancelado'), ('Devolvido', 'Devolvido')], default='Pendente', max_length=12)),
                ('automovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automovel.automovel')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
