# Generated by Django 4.2.3 on 2023-07-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('finalizado', 'Finalizado')], default='pendente', max_length=12),
        ),
    ]
