# Generated by Django 4.2.3 on 2023-07-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0003_locacao_hora_devolucao_locacao_hora_locacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='hora_devolucao',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='hora_locacao',
            field=models.TimeField(),
        ),
    ]
