# Generated by Django 4.2.3 on 2023-07-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0005_alter_locacao_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('locacado', 'Em locação'), ('confirmado', 'Confirmado'), ('finalizado', 'Finalizado')], default='pendente', max_length=12),
        ),
    ]
