# Generated by Django 4.2.3 on 2023-07-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0006_alter_locacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('retirado', 'Retirado'), ('cancelado', 'Cancelado'), ('devolvido', 'Devolvido')], default='pendente', max_length=12),
        ),
    ]
