# Generated by Django 4.2.3 on 2023-07-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0007_alter_locacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Petirado', 'Retirado'), ('Pancelado', 'Cancelado'), ('Pevolvido', 'Devolvido')], default='Pendente', max_length=12),
        ),
    ]
