# Generated by Django 4.2.3 on 2023-07-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0008_alter_locacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Retirado', 'Retirado'), ('Cancelado', 'Cancelado'), ('Devolvido', 'Devolvido')], default='Pendente', max_length=12),
        ),
    ]
