# Generated by Django 4.2.3 on 2023-07-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0009_alter_locacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='hora_devolucao',
            field=models.TimeField(verbose_name='Hora de Devolução'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='hora_locacao',
            field=models.TimeField(verbose_name='Hora de Locação'),
        ),
    ]
