# Generated by Django 4.2.3 on 2023-07-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0010_alter_locacao_hora_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='quilometragem',
            field=models.IntegerField(default=100),
        ),
    ]
