# Generated by Django 4.2.3 on 2023-07-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0011_alter_locacao_quilometragem'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='limite_km_dia',
            field=models.IntegerField(default=100),
        ),
    ]
