# Generated by Django 4.2.3 on 2023-08-09 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0013_alter_locacao_cliente_alter_locacao_quilometragem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='data_devolucao',
            field=models.DateField(default=datetime.date, verbose_name='Data de Devolução'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='data_locacao',
            field=models.DateField(default=datetime.date, verbose_name='Data de Locação'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='hora_devolucao',
            field=models.TimeField(default=1691619462.1789777, verbose_name='Hora de Devolução'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='hora_locacao',
            field=models.TimeField(default=1691619462.1789777, verbose_name='Hora de Locação'),
        ),
    ]
